# Generated by Django 4.0 on 2022-05-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_curso_entregable_alter_estudiante_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name_plural': 'profesores'},
        ),
        migrations.RenameField(
            model_name='entregable',
            old_name='entrgado',
            new_name='entregado',
        ),
    ]
